In [3]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\lucas.scarvalho\appdata\roaming\python\python313\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lucas.scarvalho\appdata\roaming\python\python313\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lucas.scarvalho\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\lucas.scarvalho\appdata\roaming\python\python313\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\lucas.scarvalho\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\users\lucas.scarvalho\appdata\roaming\python\python313\site-packages (2.5.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
import pandas as pd
import numpy as np
df_2024_1 = pd.read_csv("ca-2024-01.csv", sep=';', decimal=',')
df_2024_2 = pd.read_csv("ca-2024-02.csv", sep=';', decimal=',')
df_2025_1 = pd.read_csv("ca-2025-01.csv", sep=';', decimal=',')
df_2025_2 = pd.read_csv("ca-2025-02.csv", sep=';', decimal=',')

C:\Users\lucas.scarvalho\AppData\Local\Temp\ipykernel_5892\3749092172.py:5: DtypeWarning: Columns (0: Regiao - Sigla, 1: Estado - Sigla, 2: Municipio, 3: Revenda, 4: CNPJ da Revenda, 5: Nome da Rua, 6: Numero Rua, 7: Complemento, 8: Bairro, 9: Cep, 10: Produto, 11: Data da Coleta, 12: Unidade de Medida, 13: Bandeira) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2025_1 = pd.read_csv("ca-2025-01.csv", sep=';', decimal=',')

In [18]:
df = pd.concat([df_2024_1, df_2024_2,df_2025_1, df_2025_2],ignore_index=True)
print(df.shape) 
display(df.head())

(1712267, 16)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA,01/01/2024,5.68,NaN,R$ / litro,VIBRA
1,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA ADITIVADA,01/01/2024,5.68,NaN,R$ / litro,VIBRA
2,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,DIESEL S10,01/01/2024,5.93,NaN,R$ / litro,VIBRA
3,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,ETANOL,01/01/2024,3.99,NaN,R$ / litro,VIBRA
4,NE,AL,ARAPIRACA,AUTO POSTO SAO FRANCISCO LTDA,12.706.529/0001-04,RUA SAO FRANCISCO,274,NaN,CENTRO,57300-080,GASOLINA,01/01/2024,5.48,NaN,R$ / litro,VIBRA

In [74]:
#######EXERCICIO 2##########
df_rj_gas_rj = df.loc[(df['Estado - Sigla'] == 'RJ') &(df['Produto'] == 'GASOLINA')]
df_munic_gas_rj=df_rj_gas_rj.groupby('Revenda')['Valor de Venda'].mean().reset_index()
df_munic_gas_rj_sort=df_munic_gas_rj.sort_values(by='Valor de Venda', ascending=False)
df_munic_gas_rj_sort

                                               Revenda  Valor de Venda
690                        POSTO JARDIM OCEANICO LTDA.        7.750674
76   AUTO POSTO DE COMBUSTIVEIS M C 2000 DE SANTA I...        7.415000
776                        POSTO SATURNO FRIBURGO LTDA        6.824444
1                   A C TRANCOZO M B COMBUSTIVEIS LTDA        6.742157
304  COMERCIO DE PETROLEO E DERIVADOS COND DO RIO N...        6.713529
..                                                 ...             ...
668                             POSTO FLAMAREDI EIRELI        5.282000
571              POSTO DE GASOLINA JARDIM SULACAP LTDA        5.226364
569              POSTO DE GASOLINA JAGUAR DO ANIL LTDA        5.156667
567                     POSTO DE GASOLINA ITAJUBA LTDA        5.090000
560                        POSTO DE GASOLINA GALP LTDA        5.090000

[872 rows x 2 columns]

In [110]:
########EXERCICIO 3#######
array_rj= np.array(df_munic_gas_rj['Valor de Venda'])
q1 = np.percentile(array_rj, 25)
q3 = np.percentile(array_rj, 75)
iqr= q3 - q1
limite_superior = q3 + (1.5 * iqr)
limite_inferior = q1 - (1.5 * iqr)

outliers_sup = df_munic_gas_rj.query("Valor de Venda > @limite_superior")

SyntaxError: invalid syntax (<unknown>, line 1)

In [ ]:
maior_preco=df_rj_gas_rj.sort_values(by='Valor de Venda',ascending=False)

array_gasolina_rj = np.array(df_rj_gas_rj ['Valor de Venda'])

In [ ]:
media = np.mean(array_gasolina_rj)
mediana = np.median(array_gasolina_rj)
comprimento= (media-mediana)/mediana

q1=np.percentile(array_gasolina_rj,25)
q2=np.percentile(array_gasolina_rj,50)
q3=np.percentile(array_gasolina_rj,75)



print(f'a media é {media} e a mediana é {mediana} e o comprimento é {comprimento}')