In [61]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\lucas.scarvalho\appdata\roaming\python\python313\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lucas.scarvalho\appdata\roaming\python\python313\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lucas.scarvalho\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\lucas.scarvalho\appdata\roaming\python\python313\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\lucas.scarvalho\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [62]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\users\lucas.scarvalho\appdata\roaming\python\python313\site-packages (2.5.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [63]:
import pandas as pd
import numpy as np
df_2024_1 = pd.read_csv("2024.01.csv", sep=';', decimal=',')
df_2024_2 = pd.read_csv("2024.02.csv", sep=';', decimal=',')
df_2025_1 = pd.read_csv("2025.01.csv", sep=';', decimal=',')
df_2025_2 = pd.read_csv("2025.02.csv", sep=';', decimal=',')

C:\Users\lucas.scarvalho\AppData\Local\Temp\ipykernel_26052\3457609769.py:5: DtypeWarning: Columns (0: Regiao - Sigla, 1: Estado - Sigla, 2: Municipio, 3: Revenda, 4: CNPJ da Revenda, 5: Nome da Rua, 6: Numero Rua, 7: Complemento, 8: Bairro, 9: Cep, 10: Produto, 11: Data da Coleta, 12: Unidade de Medida, 13: Bandeira) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2025_1 = pd.read_csv("2025.01.csv", sep=';', decimal=',')

In [64]:
df = pd.concat([df_2024_1, df_2024_2,df_2025_1, df_2025_2],ignore_index=True)
print(df.shape) 
display(df.head())

(1712267, 16)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA,01/01/2024,5.68,NaN,R$ / litro,VIBRA
1,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA ADITIVADA,01/01/2024,5.68,NaN,R$ / litro,VIBRA
2,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,DIESEL S10,01/01/2024,5.93,NaN,R$ / litro,VIBRA
3,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,ETANOL,01/01/2024,3.99,NaN,R$ / litro,VIBRA
4,NE,AL,ARAPIRACA,AUTO POSTO SAO FRANCISCO LTDA,12.706.529/0001-04,RUA SAO FRANCISCO,274,NaN,CENTRO,57300-080,GASOLINA,01/01/2024,5.48,NaN,R$ / litro,VIBRA

In [80]:
#######EXERCICIO 2##########
df_rj_gas_rj = df_rj_gas_rj.loc[(df_rj_gas_rj['Estado - Sigla'] == 'RJ') &(df_rj_gas_rj['Produto'] == 'GASOLINA')]
df_munic_gas_rj=df_rj_gas_rj.groupby('Municipio')['Valor de Venda'].mean().reset_index()
df_munic_gas_rj_sort=df_munic_gas_rj.sort_values(by='Valor de Venda', ascending=False)
df_munic_gas_rj_sort

                      Municipio  Valor de Venda
29                    TRES RIOS        6.591634
0                ANGRA DOS REIS        6.521620
18                   PETROPOLIS        6.479639
2                BARRA DO PIRAI        6.375640
11                        MACAE        6.364828
16                NOVA FRIBURGO        6.357044
10                    ITAPERUNA        6.352013
6         CAMPOS DOS GOYTACAZES        6.338306
5                     CABO FRIO        6.322089
23  SAO FRANCISCO DE ITABAPOANA        6.214804
31                VOLTA REDONDA        6.206265
1                      ARARUAMA        6.158700
27                    SAQUAREMA        6.133649
3                   BARRA MANSA        6.092928
30                      VALENCA        6.047609
26                     SAPUCAIA        5.994565
22       SANTO ANTONIO DE PADUA        5.962665
21               RIO DE JANEIRO        5.930698
13                       MARICA        5.899534
19                      RESENDE        5.885842
24                  SAO GONCALO        5.855353
20                   RIO BONITO        5.848639
8                      ITABORAI        5.842281
17                  NOVA IGUACU        5.807970
7               DUQUE DE CAXIAS        5.793860
25           SAO JOAO DE MERITI        5.780650
14                    NILOPOLIS        5.769526
15                      NITEROI        5.757424
4                  BELFORD ROXO        5.752965
12                         MAGE        5.615435
9                       ITAGUAI        5.602390
28                  TERESOPOLIS        5.508448

In [66]:
########EXERCICIO 3#######
array_rj= np.array(df_munic_gas_rj['Valor de Venda'])
q1 = np.percentile(array_rj, 25)
q3 = np.percentile(array_rj, 75)
iqr= q3 - q1
limite_superior = q3 + (1.5 * iqr)
limite_inferior = q1 - (1.5 * iqr)

In [72]:
maior_preco=df_rj_gas_rj.sort_values(by='Valor de Venda',ascending=False)

array_gasolina_rj = np.array(df_rj_gas_rj ['Valor de Venda'])

array([5.29, 5.69, 5.19, ..., 5.74, 5.89, 5.94], shape=(8306,))

In [68]:
media = np.mean(array_gasolina_rj)
mediana = np.median(array_gasolina_rj)
comprimento= (media-mediana)/mediana
minimo=np.min(array_gasolina_rj)
maximo=np.max(array_gasolina_rj)
amplitude=(maximo-minimo)

q1=np.percentile(array_gasolina_rj,25)
q2=np.percentile(array_gasolina_rj,50)
q3=np.percentile(array_gasolina_rj,75)



print(f'a media é {media} e a mediana é {mediana} e o comprimento é {comprimento} maximo {maximo}, minimo {minimo} e amplitude {amplitude}')

a media é 6.021226859491734 e a mediana é 5.99 e o comprimento é 0.005213165190606675 maximo 7.79, minimo 4.84 e amplitude 2.95

In [84]:
###Calcule a média do Valor de Venda por bairro (coluna Bairro) e ordene do maior para o menor###

df_rj_gas_rj =df.loc[(df['Municipio'] == 'RIO DE JANEIRO')& (df['Produto']=='GASOLINA')]
df_bairro_gas_rj=df_rj_gas_rj.groupby('Bairro')['Valor de Venda'].mean().reset_index()
df_bairro_gas_rj_sort=df_bairro_gas_rj.sort_values(by='Valor de Venda', ascending=False)
df_bairro_gas_rj_sort.head()

             Bairro  Valor de Venda
23         FLAMENGO        6.696667
41  JARDIM BOTANICO        6.614615
44            LAGOA        6.505385
55  PARQUE FLAMENGO        6.454706
21          ESTACIO        6.416882

In [88]:
###Aplique o IQR para identificar bairros com preços médios estatisticamente atípicos — tanto os superiores quanto os inferiores###

array_rj= np.array(df_bairro_gas_rj['Valor de Venda'])
q1 = np.percentile(array_rj, 25)
q3 = np.percentile(array_rj, 75)
iqr= q3 - q1
limite_superior = q3 + (1.5 * iqr)
limite_inferior = q1 - (1.5 * iqr)

outliers_sup =df_bairro_gas_rj .loc[df_bairro_gas_rj['Valor de Venda'] > limite_superior]
outliers_INFERIOR =df_bairro_gas_rj .loc[df_bairro_gas_rj['Valor de Venda'] < limite_inferior]
 
outliers_sup

      Bairro  Valor de Venda
23  FLAMENGO        6.696667

In [71]:
outliers_sup = df.query("Valor de Venda> @limite_superior")
outliers_inf = df.query("Valor de Venda < @limite_inferior")
outliers_sup = outliers_sup.sort_values(by='Valor de Venda', 
ascending=False)
outliers_inf = outliers_inf.sort_values(by='Valor de Venda', 
ascending=True)
display(outliers_sup)
display(outliers_inf)

SyntaxError: invalid syntax (<unknown>, line 1)