In [7]:
import pandas as pd
import numpy as np

In [8]:
url = 'https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv'
df = pd.read_csv(url, encoding= 'latin1', sep=';')
df.head(3)

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3

In [9]:
df.tail(2)

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
37997,167,6,2026,2026m06,43,5,Paraty,3303807,Interior,1,...,4.0,0.0,14,1,1,0,0,0,198,2
37998,168,6,2026,2026m06,28,5,Rio Claro,3304409,Interior,0,...,0.0,0.0,4,0,0,0,0,0,32,2

In [10]:
df.columns

Index(['cisp', 'mes', 'ano', 'mes_ano', 'aisp', 'risp', 'munic', 'mcirc',
       'regiao', 'hom_doloso', 'lesao_corp_morte', 'latrocinio', 'cvli',
       'hom_por_interv_policial', 'feminicidio', 'letalidade_violenta',
       'tentat_hom', 'tentativa_feminicidio', 'lesao_corp_dolosa', 'estupro',
       'hom_culposo', 'lesao_corp_culposa', 'roubo_transeunte',
       'roubo_celular', 'roubo_em_coletivo', 'roubo_rua', 'roubo_veiculo',
       'roubo_carga', 'roubo_comercio', 'roubo_residencia', 'roubo_banco',
       'roubo_cx_eletronico', 'roubo_conducao_saque', 'roubo_apos_saque',
       'roubo_bicicleta', 'outros_roubos', 'total_roubos', 'furto_veiculos',
       'furto_transeunte', 'furto_coletivo', 'furto_celular',
       'furto_bicicleta', 'outros_furtos', 'total_furtos', 'sequestro',
       'extorsao', 'sequestro_relampago', 'estelionato', 'apreensao_drogas',
       'posse_drogas', 'trafico_drogas', 'apreensao_drogas_sem_autor',
       'recuperacao_veiculos', 'apf', 'aaapai', 'cmp', 'cmba', 'ameaca',
       'pessoas_desaparecidas', 'encontro_cadaver', 'encontro_ossada',
       'pol_militares_mortos_serv', 'pol_civis_mortos_serv',
       'registro_ocorrencias', 'fase'],
      dtype='str')

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37999 entries, 0 to 37998
Data columns (total 65 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   cisp                        37999 non-null  int64
 1   mes                         37999 non-null  int64
 2   ano                         37999 non-null  int64
 3   mes_ano                     37999 non-null  str
 4   aisp                        37999 non-null  int64
 5   risp                        37999 non-null  int64
 6   munic                       37999 non-null  str
 7   mcirc                       37999 non-null  int64
 8   regiao                      37999 non-null  str
 9   hom_doloso                  37999 non-null  int64
 10  lesao_corp_morte            37999 non-null  int64
 11  latrocinio                  37999 non-null  int64
 12  cvli                        37999 non-null  int64
 13  hom_por_interv_policial     37999 non-null  int64
 14  feminicidio                 2877 non-null   float64
 15  letalidade_violenta         37999 non-null  int64
 16  tentat_hom                  37999 non-null  int64
 17  tentativa_feminicidio       2877 non-null   float64
 18  lesao_corp_dolosa           37999 non-null  int64
 19  estupro                     37999 non-null  int64
 20  hom_culposo                 37999 non-null  int64
 21  lesao_corp_culposa          37999 non-null  int64
 22  roubo_transeunte            37999 non-null  int64
 23  roubo_celular               37999 non-null  int64
 24  roubo_em_coletivo           37999 non-null  int64
 25  roubo_rua                   37999 non-null  int64
 26  roubo_veiculo               37999 non-null  int64
 27  roubo_carga                 37999 non-null  int64
 28  roubo_comercio              37999 non-null  int64
 29  roubo_residencia            37999 non-null  int64
 30  roubo_banco                 37999 non-null  int64
 31  roubo_cx_eletronico         37980 non-null  float64
 32  roubo_conducao_saque        37999 non-null  int64
 33  roubo_apos_saque            37999 non-null  int64
 34  roubo_bicicleta             20610 non-null  float64
 35  outros_roubos               37999 non-null  int64
 36  total_roubos                37999 non-null  int64
 37  furto_veiculos              37999 non-null  int64
 38  furto_transeunte            37999 non-null  int64
 39  furto_coletivo              37999 non-null  int64
 40  furto_celular               37999 non-null  int64
 41  furto_bicicleta             20610 non-null  float64
 42  outros_furtos               37999 non-null  int64
 43  total_furtos                37999 non-null  int64
 44  sequestro                   37999 non-null  int64
 45  extorsao                    37999 non-null  int64
 46  sequestro_relampago         37999 non-null  int64
 47  estelionato                 37999 non-null  int64
 48  apreensao_drogas            37999 non-null  int64
 49  posse_drogas                33353 non-null  float64
 50  trafico_drogas              33353 non-null  float64
 51  apreensao_drogas_sem_autor  33353 non-null  float64
 52  recuperacao_veiculos        37999 non-null  int64
 53  apf                         33353 non-null  float64
 54  aaapai                      33353 non-null  float64
 55  cmp                         33353 non-null  float64
 56  cmba                        33353 non-null  float64
 57  ameaca                      37999 non-null  int64
 58  pessoas_desaparecidas       37999 non-null  int64
 59  encontro_cadaver            37999 non-null  int64
 60  encontro_ossada             37999 non-null  int64
 61  pol_militares_mortos_serv   37999 non-null  int64
 62  pol_civis_mortos_serv       37999 non-null  int64
 63  registro_ocorrencias        37999 non-null  int64
 64  fase                        37999 non-null  int64
dtypes: float64(12), int64(50), str(3)
memory usage: 18.8 MB

In [12]:
df.head(2)

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3

In [13]:
df_furto_cel_dp = df.groupby('cisp')['furto_celular'].sum().reset_index()
df_furto_cel_dp.sort_values(by='furto_celular', ascending = False,inplace=True)
df_furto_cel_dp

     cisp  furto_celular
12     16          26111
2       5          25440
10     14          18822
8      12          17537
0       1          16127
..    ...            ...
87    104             73
77     92             65
114   138             56
131   157             55
129   155             47

[138 rows x 2 columns]

In [14]:
df_aaapai_dp = df.groupby('cisp')['aaapai'].sum().reset_index()
df_aaapai_dp = df_aaapai_dp.sort_values(by='aaapai', ascending = False)
df_aaapai_dp

     cisp  aaapai
104   126  3713.0
8      12  3657.0
10     14  3365.0
65     74  3349.0
12     16  3218.0
..    ...     ...
130   156    19.0
129   155    16.0
131   157    14.0
94    111    13.0
77     92    12.0

[138 rows x 2 columns]

In [15]:
df_roubo_veiculo_dp = df.groupby('cisp')['roubo_veiculo'].sum().reset_index()
df_roubo_veiculo_dp = df_roubo_veiculo_dp.sort_values(by='roubo_veiculo', ascending = False)
df_roubo_veiculo_dp

     cisp  roubo_veiculo
52     59          37780
57     64          32839
35     39          29663
23     27          27920
30     34          27543
..    ...            ...
77     92              8
116   140              8
115   139              7
113   137              6
114   138              2

[138 rows x 2 columns]

In [31]:

munic_pedido=['Belford ROxo','Nova Iguaçu','Queimados']

df_bel_nov_quei=df.loc[df['munic'].isin(munic_pedido)]

In [24]:
df_roubo_veiculo_dp_bel=df_bel.groupby('cisp')['roubo_veiculo'].sum().reset_index()
df_roubo_veiculo_dp_bel=df_roubo_veiculo_dp_bel.sort_values(by='roubo_veiculo',ascending=False)
df_roubo_veiculo_dp_bel

Empty DataFrame
Columns: [cisp, roubo_veiculo]
Index: []

In [33]:
array_furto_cel_cdp= np.array(df_furto_cel_dp['furto_celular'])
array_furto_cel_cdp

array([26111, 25440, 18822, 17537, 16127, 15278, 14773, 14436, 14247,
       12833, 12231,  8899,  8849,  8701,  8342,  8223,  8132,  7804,
        7360,  7261,  7040,  6971,  6669,  6617,  6185,  5770,  5655,
        5596,  5458,  5357,  5041,  4979,  4758,  4755,  4708,  4652,
        4162,  4126,  4120,  4052,  3885,  3795,  3779,  3762,  3531,
        3421,  3376,  3286,  3142,  2997,  2968,  2869,  2707,  2681,
        2611,  2416,  2393,  2353,  2322,  2207,  2158,  2150,  2139,
        2132,  2089,  1836,  1836,  1825,  1744,  1714,  1663,  1630,
        1546,  1485,  1473,  1441,  1390,  1376,  1309,  1250,  1149,
        1096,  1050,  1042,  1035,   907,   836,   822,   810,   752,
         743,   662,   654,   633,   632,   626,   583,   565,   516,
         513,   506,   499,   461,   453,   451,   442,   410,   405,
         385,   374,   369,   362,   357,   304,   302,   260,   244,
         238,   213,   206,   203,   197,   172,   167,   155,   147,
         129,   124,   116,   111,    90,    83,    73,    73,    65,
          56,    55,    47])

In [41]:
media=np.mean(array_furto_cel_cdp)
mediana=np.median(array_furto_cel_cdp)
q1=np.percentile(array_furto_cel_cdp,25)
q2=np.percentile(array_furto_cel_cdp,50)
q3=np.percentile(array_furto_cel_cdp,75)

print(f'Media {media}\n Mediana {mediana}')
print(f'q1:{q1}')
print(f'q2:{q2}')
print(f'q3:{q3}')

Media 3534.014492753623
 Mediana 1729.0
q1:455.0
q2:1729.0
q3:4694.0

In [57]:
distancia=(media-mediana)/mediana
print(f'bqbq {distancia:.2%}')

bqbq 104.40%

In [48]:
df_roubo_veiculo_dp = df.groupby('cisp')['roubo_veiculo'].sum().reset_index()
df_roubo_veiculo_dp=df_roubo_veiculo_dp.sort_values(by='roubo_veiculo',ascending=False)
df_roubo_veiculo_dp

     cisp  roubo_veiculo
52     59          37780
57     64          32839
35     39          29663
23     27          27920
30     34          27543
..    ...            ...
77     92              8
116   140              8
115   139              7
113   137              6
114   138              2

[138 rows x 2 columns]

In [49]:
array_roubo_veiculo_dp= np.array(df_roubo_veiculo_dp['roubo_veiculo'])
media_veiculo=np.mean(array_roubo_veiculo_dp)
mediana_veiculo=np.median(array_roubo_veiculo_dp)
q1_veiculo=np.percentile(array_roubo_veiculo_dp,25)
q2_veiculo=np.percentile(array_roubo_veiculo_dp,50)
q3_veiculo=np.percentile(array_roubo_veiculo_dp,75)

In [51]:
print(f'Media {media_veiculo}\n Mediana {mediana_veiculo}')
print(f'q1:{q1_veiculo}')
print(f'q2:{q2_veiculo}')
print(f'q3:{q3_veiculo}')

Media 5250.840579710145
 Mediana 1227.0
q1:103.75
q2:1227.0
q3:8117.5

In [69]:
df_aaapai_dp = df.groupby('cisp')['aaapai'].sum().reset_index()
df_aaapai_dp = df_aaapai_dp.sort_values(by='aaapai', ascending = False)
df_aaapai_dp

     cisp  aaapai
104   126  3713.0
8      12  3657.0
10     14  3365.0
65     74  3349.0
12     16  3218.0
..    ...     ...
130   156    19.0
129   155    16.0
131   157    14.0
94    111    13.0
77     92    12.0

[138 rows x 2 columns]

In [73]:
array_aaapai_dp= np.array(df_aaapai_dp['aaapai'])
media_aaapi=np.mean(array_aaapai_dp)
mediana_aaapi=np.median(array_aaapai_dp)
q1_aaapi=np.percentile(array_aaapai_dp,25)
q2_aaapi=np.percentile(array_aaapai_dp,50)
q3_aaapi=np.percentile(array_aaapai_dp,75)
distancia_aaaapai=(media_aaapi-mediana_aaapi)/mediana_aaapi
print(f'rrrr {distancia_aaaapai:.2%}')

rrrr 32.45%