In [6]:
import pandas as pd
import numpy as np

In [ ]:
####CORREÇÃO DA PLANILHA DE CLIENTES######
df_clientes = pd.read_csv('clientes.csv', sep=';')
print(df_clientes.shape)
display(df_clientes.head(5))
display(df_clientes.tail(3))

(301, 6)

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
0,1,Otavio Reis,São Paulo,SP,18-25,PJ
1,2,Larissa Sousa,Curitiba,SC,18-25,pessoa fisica
2,3,Tatiana Coelho,Rio de Janeiro,CE,65+,Corporativo
3,4,Wilson Duarte,Brasília,AM,26-35,corporativo
4,5,Gabriela Lima,Rio de Janeiro,SP,46-55,Pessoa Física

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
298,299,Vanessa Cavalcanti,Curitiba,AM,46-55,Pessoa Física
299,300,Julia Monteiro,Brasília,PR,36-45,Corporativo
300,47,Carlos Neto,Niterói,RJ,36-45,Corporativo

In [6]:
df_clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_cliente     301 non-null    int64
 1   nome           301 non-null    str
 2   cidade_origem  301 non-null    str
 3   estado_origem  301 non-null    str
 4   faixa_etaria   272 non-null    str
 5   tipo_cliente   301 non-null    str
dtypes: int64(1), str(5)
memory usage: 14.2 KB

In [7]:
df_clientes.isnull().sum()

id_cliente        0
nome              0
cidade_origem     0
estado_origem     0
faixa_etaria     29
tipo_cliente      0
dtype: int64

In [10]:
df_clientes['tipo_cliente'].value_counts()

tipo_cliente
Corporativo      127
Pessoa Física    103
corporativo       17
PJ                15
pessoa fisica     15
PF                14
pf                10
Name: count, dtype: int64

In [13]:
# Mapear variações para o valor correto e susbstitui pelo valores certos
mapa = {
    'corporativo':                     'Corporativo',
    'pessoa fisica':                   'Pessoa Física',
    'PF':                              'Pessoa Física',
    'pf' :                              'Pessoa Física'

}
df_clientes['tipo_cliente'] = df_clientes['tipo_cliente'].map(mapa).fillna(df_clientes['tipo_cliente'])#joga as informações do dicionario mapa no df. filne mantem os valores corretos que não precisam de substituição

print('Após mapeamento:')
print(sorted(df_clientes['tipo_cliente'].unique()))

Após mapeamento:
['Corporativo', 'PJ', 'Pessoa Física']

In [12]:
df_clientes.loc[
    df_clientes.duplicated(subset=['nome'], keep=False),
    'nome'
]

0             Otavio Reis
1           Larissa Sousa
2          Tatiana Coelho
3           Wilson Duarte
4           Gabriela Lima
              ...
296         Roberta Leite
297         Eduardo Lopes
298    Vanessa Cavalcanti
299       Julia Monteiro
300           Carlos Neto
Name: nome, Length: 285, dtype: str

In [13]:
# nome: verificar espaços invisíveis
print('\n--- nomes com espaço nas bordas ---')
mascara = df_clientes['nome'].str.startswith(' ') | df_clientes['nome'].str.endswith(' ')
(df_clientes.loc[mascara, 'nome'].tolist())

--- nomes com espaço nas bordas ---

['  Henrique Rocha ',
 'Thiago Matos  ',
 '  Diego Ferreira ',
 'Xuxa Farias  ',
 '  Julia Monteiro ',
 '  Carlos Neto ',
 '  Diego Ferreira ',
 'Ximena Godoi  ',
 '  Thiago Matos ',
 'Otavio Reis  ',
 '  Rafael Cardoso ',
 '  Ursula Pinto ',
 '  Otavio Reis ',
 'Ana Silva  ',
 '  João Pereira ',
 'Felipe Oliveira  ',
 '  Lucas Souza ',
 '  Roberta Leite ',
 '  Carlos Neto ',
 'Gustavo Vieira  ',
 '  Ximena Godoi ',
 'Xuxa Farias  ',
 '  Roberta Leite ',
 '  João Pereira ',
 '  Vanessa Cavalcanti ',
 'Sara Teixeira  ',
 '  Lucas Souza ',
 'Ulisses Brito  ',
 '  Ana Silva ',
 '  Julia Monteiro ']

In [16]:
df_clientes['nome'] = df_clientes['nome'].str.strip().str.title()
print(sorted(df_clientes['nome'].unique()))

['Abel Correia', 'Ana Silva', 'Beatriz Dias', 'Bruno Costa', 'Carla Mendes', 'Carlos Neto', 'Daniela Ramos', 'Diego Ferreira', 'Eduardo Lopes', 'Elena Santos', 'Felipe Oliveira', 'Fernanda Cruz', 'Gabriela Lima', 'Gustavo Vieira', 'Helena Borges', 'Henrique Rocha', 'Isabela Martins', 'Ivan Azevedo', 'João Pereira', 'Julia Monteiro', 'Karen Alves', 'Kleber Pires', 'Larissa Sousa', 'Lucas Souza', 'Marcos Andrade', 'Marina Barbosa', 'Natalia Campos', 'Nicolas Cunha', 'Olivia Freitas', 'Otavio Reis', 'Patricia Vaz', 'Paulo Ribeiro', 'Quezia Nunes', 'Quincy Braga', 'Rafael Cardoso', 'Roberta Leite', 'Samuel Fonseca', 'Sara Teixeira', 'Tatiana Coelho', 'Thiago Matos', 'Ulisses Brito', 'Ursula Pinto', 'Vanessa Cavalcanti', 'Victor Gomes', 'Wesley Araujo', 'Wilson Duarte', 'Ximena Godoi', 'Xuxa Farias', 'Yuri Castro', 'Zara Moraes']

In [18]:
#######CORREÇÃO DA PLANILHA DE FUNCIONARIOS#######
df_funcionarios = pd.read_csv('funcionarios.csv', sep=';')
df_funcionarios

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,1,1,Gabriela Lima,Auxiliar de Limpeza,Governança,"""2.139,00""",2020-10-05
1,2,1,Abel Correia,Segurança,Segurança,"""1.746,00""",2021-12-29
2,3,1,Sara Teixeira,analista financeiro,Financeiro,"""5.356,00""",2022-03-01
3,4,1,Julia Monteiro,Auxiliar de Limpeza,Governança,"""2.070,00""",2019-06-10
4,5,1,Daniela Ramos,Auxiliar de Limpeza,Governança,"""1.572,00""",2018-10-16
...,...,...,...,...,...,...,...
129,130,12,Fernanda Cruz,Manutenção,Manutenção,"""2.221,00""",2020-08-16
130,131,12,Abel Correia,Gerente,Administração,"""8.404,00""",2018-10-28
131,132,12,Yuri Castro,Recepcionista,Recepção,"""2.700,00""",2021-01-22
132,133,12,Yuri Castro,segurança,Segurança,"""1.976,00""",2021-10-08
133,134,12,Eduardo Lopes,Recepcionista,Recepção,"""2.442,00""",2023-02-17

In [19]:
display(df_funcionarios.dtypes)

id_funcionario    int64
id_unidade        int64
nome                str
cargo               str
departamento        str
salario             str
data_admissao       str
dtype: object

In [20]:
df_funcionarios.isnull().sum()

id_funcionario    0
id_unidade        0
nome              0
cargo             0
departamento      0
salario           6
data_admissao     0
dtype: int64

In [22]:
df_funcionarios[df_funcionarios.isnull()     # Gera True/False para cada dado (True = nulo)
   .any(axis=1)]

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
8,9,1,Bruno Costa,Auxiliar de Limpeza,Governança,NaN,2021-11-02
13,14,1,Yuri Castro,Analista Financeiro,Financeiro,NaN,2022-12-31
36,37,4,Larissa Sousa,cozinheiro,Alimentos e Bebidas,NaN,2019-09-29
42,43,4,Wilson Duarte,Analista Financeiro,Financeiro,NaN,2022-01-07
91,92,9,Wilson Duarte,Gerente,Administração,NaN,2024-02-29
103,104,10,Vanessa Cavalcanti,COZINHEIRO,Alimentos e Bebidas,NaN,2024-05-27